SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
-- ITEM_TREE 테이블에서 ITEM_ID가 다른 아이템의 PARENT_ITEM_ID로 등장하지 않는 아이템 찾기
-- 그 결과를 ITEM_INFO와 조인
WHERE T.ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY I.ITEM_ID DESC
;
