SELECT 
    P.PRODUCT_CODE,
    SUM(P.PRICE * O.SALES_AMOUNT) AS TOTAL_SALES
FROM
    PRODUCT P
JOIN
    OFFLINE_SALE O
ON
    P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY
    P.PRODUCT_CODE
ORDER BY
    TOTAL_SALES DESC,
    P.PRODUCT_CODE ASC;