SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' or SEX_UPON_OUTCOME LIKE 'Neutered%'
) J
ON I.ANIMAL_ID = J.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY I.ANIMAL_ID
;