SELECT 
    I.REST_ID, 
    I.REST_NAME, 
    I.FOOD_TYPE, 
    I.FAVORITES, 
    I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE -- 리뷰 평균 점수를 소수점 3자리에서 반올림
FROM REST_INFO I
INNER JOIN REST_REVIEW R
    ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC   -- 평균 점수 기준 내림차순 정렬, 같다면 즐겨찾기순으로 정렬
;