SELECT 
    CAR_ID, 
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION        -- 대여 기간은 시작일과 종료일을 포함해서 계산해야 함
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 
    CAR_ID
HAVING 
    AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY 
    2 DESC, 1 DESC
;