SELECT COUNT(*) AS FISH_COUNT, FNI.FISH_NAME
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY FNI.FISH_NAME          -- 이름 별로 그룹핑
ORDER BY FISH_COUNT DESC        -- 잡은 수 내림차순 정렬
;