SELECT H.FLAVOR
FROM FIRST_HALF H
-- JULY 테이블에서 맛 별로 총 주문량을 합산
-- INNER JOIN으로 두 테이블 모두에 존재하는 FLAVOR만 대상
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS 'TOTAL_ORDER'
    FROM JULY
    GROUP BY FLAVOR
) J
ON H.FLAVOR = J.FLAVOR
-- 상위 3개 맛만 출력
ORDER BY H.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3
;