SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W'          -- 생일이 3월인 여성 회원만 조회
    AND TO_CHAR(DATE_OF_BIRTH, 'MM') = '03'
    AND TLNO IS NOT NULL    -- 전화번호가 NULL이면 출력대상에서 제외
ORDER BY MEMBER_ID          -- 회원 ID를 기준으로 오름차순 정렬
;