SELECT USER_ID, 
       NICKNAME, 
       SUM(PRICE) AS TOTAL_SALES
FROM (
    SELECT WRITER_ID, PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
) B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY 3
;