SELECT
    MONTH(M.START_DATE) AS MONTH,
    M.CAR_ID,
    COUNT(M.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY M
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
) F ON M.CAR_ID = F.CAR_ID
WHERE M.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, M.CAR_ID
HAVING RECORDS >= 1
ORDER BY MONTH, M.CAR_ID DESC
;
