SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S
-- SKILL_CODE 값이 S.CODE 값을 포함하는지 확인
-- 즉, BITWISE AND 연산을 사용하여 특정 비트가 포함되어 있는지 검사
ON (D.SKILL_CODE & S.CODE) = S.CODE
WHERE S.NAME IN ('Python', 'C#')
ORDER BY D.ID
;
