SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE CATEGORY = '경제'          -- '경제' 카테고리에 속하는 도서들 
ORDER BY PUBLISHED_DATE         -- 출판일을 기준을 오름차순
;